version: 2
jobs:
  build:
      docker:
        - image: bitriseio/android-ndk:v2018_05_05-06_07-b990
      working_directory: ~/code
      environment:
        JVM_OPTS: -Xmx3200m
      steps:
        - checkout
        - run:
            name: Assemble build
            command: ./gradlew :app:assembleDebug
        - run:
            name: Upload to HockeyApp
            command: sh ./.circleci/hockeyapp-upload.sh
